name: Run Re Target
description: Runs a Re build system target

inputs:
  path:
    description: The path to the project
    default: .

  target:
    description: The target to run (if empty, runs the default target or errors out)
    default: ''

  cmdline:
    description: The run command line (can include Re options as well)
    default: ''

  arch:
    description: Build architecture
    default: x64
    
  configuration:
    description: Build configuration
    default: release

  re-executable:
    description: The Re executable to use
    default: re

runs:
  using: 'composite'
  steps:
    - run: ${{ inputs.re-executable }} run --msg-level problems --no-run-choice true --arch ${{ inputs.arch }} --configuration ${{ inputs.configuration }} --path ${{ inputs.path }} ${{ inputs.target }} ${{ inputs.cmdline }}
      shell: bash
